name = "esme"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
node_socket_client = ">= 1.0.0 and < 2.0.0"
gpsd_json = ">= 1.0.0 and < 2.0.0"
gsv = ">= 1.4.0 and < 2.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
plinth = ">= 0.4.8 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
